name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  skip_redundant_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Workflows
        uses: styfle/cancel-workflow-action@0.9.1
